variables:
  GITLAB_CI_IMAGE_DEBIAN: 'debian:buster'
stages:
  - build
  
build:
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -qq -y gnupg libcurl4
    - echo 'deb http://download.opensuse.org/repositories/home:/librespace:/satnogs-unstable/Debian_10/ /' > /etc/apt/sources.list.d/home:librespace:satnogs-unstable.list
    - apt-key adv --fetch-keys https://download.opensuse.org/repositories/home:librespace:satnogs-unstable/Debian_10/Release.key
    - apt-get update -qq -y
    - >
      apt-get install -q -y
      cmake
      git
      gr-soapy
      gr-satnogs
      pkg-config
      python3
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make install
debian:
  stage: build
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  before_script:
    - apt-get update -qq
    - apt-get install -qq -y gnupg libcurl4
    - echo 'deb http://download.opensuse.org/repositories/home:/librespace:/satnogs/Debian_10/ /' > /etc/apt/sources.list.d/home:librespace:satnogs.list
    - apt-key adv --fetch-keys https://download.opensuse.org/repositories/home:librespace:satnogs/Debian_10/Release.key
    - apt-get update
    - apt-get install -y devscripts git-buildpackage
  script:
    - mk-build-deps -i -r -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
    - PACKAGE_VERSION="$CI_COMMIT_TAG"
    - PACKAGE_VERSION="${PACKAGE_VERSION:-$(git describe --abbrev=8 2>/dev/null | tr '-' '+' | cut -c '2-' || true)}"
    - PACKAGE_VERSION="${PACKAGE_VERSION#v}"
    - |
      [ -z "$PACKAGE_VERSION" ] || {
          dch -b -M -v "${PACKAGE_VERSION}-1" "Bump to version '${PACKAGE_VERSION}-1'"
          dch -r -m ""
      }
    - gbp buildpackage -us -uc --git-upstream-tag='HEAD' --git-ignore-branch --git-ignore-new
    - mkdir artifacts
    - cp -a ../*.{deb,dsc,build,buildinfo,changes,orig.tar.gz} artifacts/
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - artifacts
