variables:
  GITLAB_CI_IMAGE_DEBIAN: 'debian:buster'
  GITLAB_CI_APT_REPOSITORY: 'deb http://download.opensuse.org/repositories/home:/librespace:/satnogs/Debian_10/ /'
  GITLAB_CI_APT_KEY_URL: 'https://download.opensuse.org/repositories/home:librespace:satnogs/Debian_10/Release.key'
stages:
  - build
  - deploy
debian:
  stage: build
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  before_script:
    - apt-get update -qq
    - apt-get install -qq -y gnupg libcurl4
    - echo "$GITLAB_CI_APT_REPOSITORY" > /etc/apt/sources.list.d/home:librespace:satnogs.list
    - apt-key adv --fetch-keys "$GITLAB_CI_APT_KEY_URL"
    - apt-get update
    - apt-get install -y devscripts git-buildpackage
  script:
    - mk-build-deps -i -r -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
    - PACKAGE_VERSION="$CI_COMMIT_TAG"
    - PACKAGE_VERSION="${PACKAGE_VERSION:-$(git describe --abbrev=8 2>/dev/null | tr '-' '+' | cut -c '2-' || true)}"
    - PACKAGE_VERSION="${PACKAGE_VERSION#v}"
    - |
      [ -z "$PACKAGE_VERSION" ] || {
          dch -b -M -v "${PACKAGE_VERSION}-1" "Bump to version '${PACKAGE_VERSION}-1'"
          dch -r -m ""
      }
    - gbp buildpackage -us -uc --git-upstream-tag='HEAD' --git-ignore-branch --git-ignore-new
    - mkdir artifacts
    - cp -a ../*.{deb,diff.gz,dsc,build,buildinfo,changes,orig.tar.gz} artifacts/
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - artifacts
deploy:
  stage: deploy
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  before_script:
    - apt-get update
    - apt-get install -y osc
  script:
    - |
      cat <<-EOF > ~/.oscrc
      [general]
      apiurl = https://api.opensuse.org
      [https://api.opensuse.org]
      user = $OBS_USER
      pass = $OBS_PASS
      EOF
    - |
      PROJECT="${CI_COMMIT_TAG:+home:librespace:satnogs}"
      PROJECT="${PROJECT:-home:librespace:satnogs-unstable}"
      BASE_DIR="$(pwd)"
      OSC_WORKDIR="$BASE_DIR/osc_workdir"
      ARTIFACTS_DIR="$BASE_DIR/artifacts"
      DSC_FILENAME=$(basename $(ls "$ARTIFACTS_DIR"/*.dsc))
      PACKAGE="${CI_COMMIT_TAG:+${DSC_FILENAME%.dsc}}"
      PACKAGE="${PACKAGE:-${DSC_FILENAME%%_*}}"
      mkdir -p "$OSC_WORKDIR"
      cd "$OSC_WORKDIR"
      [ -d "$PROJECT" ] || osc co "$PROJECT"
      cd "$PROJECT"
      [ -d "$PACKAGE" ] || osc mkpac "$PACKAGE"
      rm -f "$PACKAGE"/*.{dsc,diff.gz,orig.tar.gz}
      cp -a "$ARTIFACTS_DIR"/*.{dsc,diff.gz,orig.tar.gz} "$PACKAGE"
      osc addremove -r
      osc ci -m "$DSC_FILENAME"
      cd "$BASE_DIR"
      rm -r "$OSC_WORKDIR"
  only:
    refs:
      - master
      - tags
    variables:
      - $OBS_USER
      - $OBS_PASS
