variables:
  GITLAB_CI_IMAGE_DEBIAN: 'debian:buster'
stages:
  - build
  
build:
  image: ${GITLAB_CI_IMAGE_DEBIAN}
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -qq -y gnupg libcurl4
    - echo 'deb http://download.opensuse.org/repositories/home:/librespace:/satnogs-unstable/Debian_10/ /' > /etc/apt/sources.list.d/home:librespace:satnogs-unstable.list
    - apt-key adv --fetch-keys https://download.opensuse.org/repositories/home:librespace:satnogs-unstable/Debian_10/Release.key
    - apt-get update -qq -y
    - >
      apt-get install -q -y
      cmake
      git
      gr-soapy
      gr-satnogs
      pkg-config
      python3
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make install
